// Client-safe DNS provider constants shared between the server JMAP layer
// (`src/server/stalwart-dns.ts`) and the wizard UI (`DnsStep`). Kept in a
// dependency-free module so importing it into a client component never pulls a
// server-only module (node:fs, JMAP transport) into the browser bundle.
//
// Captured from the v0.16 schema enum DnsServerBootstrapType. The enum lists 71
// entries; the deprecated placeholder ("Deprecated1") is omitted here, leaving 70.
// See docs/superpowers/specs/2026-06-09-stalwart-api-capture.md §6.
export const DNS_PROVIDERS = [
  "Manual",
  "Tsig",
  "Cloudflare",
  "DigitalOcean",
  "DeSEC",
  "Ovh",
  "Bunny",
  "Porkbun",
  "Dnsimple",
  "Spaceship",
  "Route53",
  "GoogleCloudDns",
  "Alidns",
  "ArvanCloud",
  "Autodns",
  "AzureDns",
  "BaiduCloud",
  "BluecatV2",
  "ClouDns",
  "Constellix",
  "Cpanel",
  "Ddnss",
  "DnsMadeEasy",
  "Domeneshop",
  "Dreamhost",
  "DuckDns",
  "Dynu",
  "EasyDns",
  "EdgeDns",
  "Exoscale",
  "FreeMyIp",
  "GandiV5",
  "Gcore",
  "Glesys",
  "Godaddy",
  "Hetzner",
  "HostingDe",
  "Hostinger",
  "HuaweiCloud",
  "Hurricane",
  "IbmCloud",
  "Infoblox",
  "Infomaniak",
  "Inwx",
  "Ionos",
  "Ipv64",
  "Joker",
  "Lightsail",
  "Linode",
  "LuaDns",
  "MythicBeasts",
  "Namecheap",
  "NameDotCom",
  "NameSilo",
  "Netcup",
  "Netlify",
  "Nifcloud",
  "Ns1",
  "OracleCloud",
  "Plesk",
  "Safedns",
  "Scaleway",
  "TencentCloud",
  "Transip",
  "UltraDns",
  "Vercel",
  "Volcengine",
  "Vultr",
  "WebSupport",
  "YandexCloud",
] as const

export type DnsProvider = (typeof DNS_PROVIDERS)[number]
